# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main_optimized.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/Icon SVGs/bg icon_256 x 256.svg', 'assets'),
        ('assets/Icon PNGs', 'assets/Icon PNGs'),  # Bundle custom PNG icons
        ('assets/icon.ico', 'assets'),
        ('.venv/Lib/site-packages/rembg', 'rembg'),
        ('.venv/Lib/site-packages/onnxruntime', 'onnxruntime'),
    ],
    hiddenimports=[
        'rembg',
        'rembg.__init__',
        'rembg.bg',
        'rembg.session_factory',
        'rembg.sessions',
        'rembg.sessions.base',
        'rembg.sessions.u2net',
        'rembg.sessions.u2netp',
        'rembg.sessions.silueta',
        'rembg.sessions.isnet',
        'rembg.sessions.sam',
        'rembg.new_session',
        'onnxruntime',
        'onnxruntime.capi',
        'onnxruntime.capi.onnxruntime_pybind11_state',
        'onnxruntime.capi._pybind_state',
        'onnxruntime.backend',
        'onnxruntime.backend.backend',
        'PIL',
        'PIL.Image',
        'PIL.ImageOps',
        'PIL.ImageFilter',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'cv2',
        'numpy',
        'skimage',
        'skimage.transform',
        'skimage.measure',
        'skimage.segmentation',
        'scipy',
        'scipy.ndimage',
        'scipy.sparse',
        'scipy.sparse.csgraph',
        'numba',
        'numba.core',
        'numba.core.types',
        'numba.typed',
        'llvmlite',
        'pooch',
        'requests',
        'tqdm',
        'huggingface_hub',
        'filelock',
        'typing_extensions',
        'packaging',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'torch',
        'torchvision'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BackgroundRemover',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # Disable UPX compression to reduce false positives
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
    version='version_info.txt'  # Add version information
)
